# Generated by Django 3.1.1 on 2020-09-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('major', models.CharField(max_length=200, null=True)),
                ('minor', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
