# Generated by Django 3.1.1 on 2020-09-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=200, null=True)),
                ('schedule_number', models.CharField(max_length=200, null=True)),
                ('date_time_held', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('instructor', models.CharField(max_length=200, null=True)),
                ('units', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=200, null=True)),
                ('prerequisites', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('office_phone', models.CharField(max_length=200, null=True)),
                ('office_number', models.CharField(max_length=200, null=True)),
                ('office_hours', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
