# Generated by Django 3.1.1 on 2020-09-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_course_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
