# Generated by Django 3.1.1 on 2020-10-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='electives',
            field=models.ManyToManyField(related_name='electives', to='school.Course'),
        ),
        migrations.AlterField(
            model_name='major',
            name='required_courses',
            field=models.ManyToManyField(related_name='required_courses', to='school.Course'),
        ),
    ]
