# Generated by Django 3.1.1 on 2020-10-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20201006_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed_courses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='completed_courses',
            name='status',
        ),
    ]
