# Generated by Django 3.1.1 on 2020-09-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200919_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
