# Generated by Django 3.1.1 on 2020-10-06 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20201006_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed_courses',
            name='course_title',
        ),
        migrations.AddField(
            model_name='completed_courses',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.course'),
        ),
        migrations.AddField(
            model_name='completed_courses',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress')], max_length=200, null=True),
        ),
    ]
