# Generated by Django 3.1.1 on 2020-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20201015_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
