# Generated by Django 3.1.1 on 2020-10-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20201015_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.major'),
        ),
    ]
