# Generated by Django 3.1.1 on 2020-10-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20201006_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress')], max_length=200, null=True)),
                ('semester_completed', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=200, null=True)),
                ('other_university', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='course',
            name='other_university',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester_completed',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.faculty'),
        ),
        migrations.DeleteModel(
            name='Completed_Courses',
        ),
        migrations.AddField(
            model_name='students_course',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.course'),
        ),
        migrations.AddField(
            model_name='students_course',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student'),
        ),
    ]
