# Generated by Django 3.1.1 on 2020-10-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_course_num_spots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_spots',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
    ]
