# Generated by Django 3.1.1 on 2020-10-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_course_seats_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seats_occupied',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
